name: Destroy pull request environment - GameGatherApi

on:
  # pull_request:
  #   types: [closed]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pull-requests: write


jobs:
  destroy:
    defaults:
      run:
        working-directory: ./terraform/pr_environments
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      - name: Terraform Format
        id: fmt
        run: terraform fmt 
        
      - name: Terraform Init
        id: init
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          echo "##[group]Terraform Init"
          echo "Initializing Terraform..."
          
          terraform init -input=false \
            -backend-config="resource_group_name=${{ secrets.AZURE_RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.AZURE_CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.AZURE_KEY }}"

      - name: Terraform Validate
        id: validate
        run: terraform validate

      - name: Terraform Destroy
        id: destroy
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform destroy -auto-approve

  # terraform_prod:
  #   if: github.event.pull_request.merged == true
  #   needs: destroy
  #   runs-on: ubuntu-latest
  #   defaults:
  #     run:
  #       working-directory: ./terraform
  #   outputs:
  #     webapp_name: ${{ steps.terraform_output.outputs.webapp_name }}
  #     resource_group_name: ${{ steps.terraform_output.outputs.resource_group_name }}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Setup Terraform
  #       uses: hashicorp/setup-terraform@v3.1.2

  #     - name: Terraform Format
  #       id: fmt
  #       run: terraform fmt 
        
  #     - name: Terraform Init
  #       id: init
  #       env:
  #         ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #         ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #         ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #         ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #       run: |
  #         echo "##[group]Terraform Init"
  #         echo "Initializing Terraform..."
          
  #         terraform init -input=false \
  #           -backend-config="resource_group_name=${{ secrets.AZURE_RESOURCE_GROUP_NAME_PROD }}" \
  #           -backend-config="storage_account_name=${{ secrets.AZURE_STORAGE_ACCOUNT_NAME_PROD }}" \
  #           -backend-config="container_name=${{ secrets.AZURE_CONTAINER_NAME_PROD }}" \
  #           -backend-config="key=${{ secrets.AZURE_KEY_PROD }}"

  #     - name: Terraform Validate
  #       id: validate
  #       run: terraform validate

  #     - name: Terraform Plan
  #       id: plan
  #       env:
  #         ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #         ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #         ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #         ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #       run: terraform plan -no-color -input=false

  #     - name: Terraform Apply
  #       id: apply
  #       run: terraform apply -auto-approve -no-color -input=false 
  #       env:
  #         ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #         ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #         ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #         ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #         ARM_USE_AZUREAD: true    

  #     - name: Terraform Output
  #       id: terraform_output
  #       run: |
  #         echo "webapp_name=$(terraform output -raw webapp_name)" >> $GITHUB_OUTPUT
  #         echo $(terraform output -raw webapp_name)
  #         echo "resource_group_name=$(terraform output -raw resource_group_name)" >> $GITHUB_OUTPUT
  #         echo $(terraform output -raw resource_group_name)
  #       env:
  #         ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #         ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  #         ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #         ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}      

  # deploy:
  #   if: github.event.pull_request.merged == true
  #   needs: terraform_prod
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write  # Wymagane uprawnienia do tworzenia releases
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4
        
  #     - name: Login to Azure
  #       run: |
  #         echo "Logging in to Azure..."
  #         az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }} --output none

  #     - name: Get run ID of "create-pull-request-environment" workflow
  #       id: get-run-id
  #       run: |
  #         echo "Fetching latest successful run ID..."
  #         RUN_ID=$(gh run list --repo ${{ github.repository }} --workflow "create-pull-request-environment.yml" --status completed --json databaseId,conclusion --jq '.[] | select(.conclusion == "success") | .databaseId' | head -n 1)
  #         echo "Detected latest successful run id: ${RUN_ID}"
  #         echo "run-id=${RUN_ID}" >> "$GITHUB_OUTPUT"
  #       env:
  #         GH_TOKEN: ${{ secrets.GH_PAT }}

  #     - name: Download artifact from build workflows
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: .net-app
  #         github-token: ${{ secrets.GH_PAT }}
  #         repository: ${{ github.repository }}
  #         run-id: ${{ steps.get-run-id.outputs.run-id }}
  #         path: ./app-artifacts  # Pobierz do konkretnego katalogu
      

  #     - name: Deploy to Azure Web App
  #       id: deploy
  #       uses: azure/webapps-deploy@v3
  #       with:
  #         app-name: ${{ needs.terraform_prod.outputs.webapp_name }}
  #         resource-group-name: ${{ needs.terraform_prod.outputs.resource_group_name }}
  #         package: ./app-artifacts  # Ścieżka do katalogu z artefaktami

  #     - name: Logout from Azure
  #       run: |
  #         az logout

  #     - name: Create ZIP archive
  #       run: |
  #         cd ./app-artifacts
  #         zip -r ../gamegather-app.zip ./*

  #     - name: Get current date
  #       id: date
  #       run: echo "date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

  #     - name: Create Release
  #       id: create_release
  #       uses: softprops/action-gh-release@v2
  #       with:
  #         tag_name: release-${{ steps.date.outputs.date }}
  #         name: Release ${{ steps.date.outputs.date }}
  #         files: gamegather-app.zip
  #         draft: false
  #         prerelease: false
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         body: |
  #           # Release notes
            
  #           Automatyczne wydanie po zmergeowaniu PR #${{ github.event.pull_request.number }}
            
  #           **PR Title**: ${{ github.event.pull_request.title }}
  #           **Merged by**: ${{ github.actor }}
  #           **Wdrożono na**: ${{ needs.terraform_prod.outputs.webapp_name }}
